version: '3.2'
services:
  rabbitmq_bootcamp:
    build:
      context: ./rabbitmq
    image: peagaa/rabbitmq_bootcamp:latest
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq_bootcamp
    networks:
      - backend
  postgres_bootcamp:
    build:
      context: ./postgres
    image: peagaa/postgres_bootcamp:latest
    ports:
      - 5432:5432
    container_name: postgres_bootcamp
    networks:
      - backend
  bootcamp-user-api:
    build:
      context: ../paulo-herbert-backend/app-user-api
      dockerfile: ../app-user-api/Dockerfile
    image: peagaa/app-user-api:latest
    ports:
      - 8081:8081
    container_name: app-user-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
    depends_on:
      - postgres_bootcamp
    networks:
      - backend
  bootcamp-integration-api:
    build:
      context: ../paulo-herbert-backend/app-integration-api
      dockerfile: ../app-integration-api/Dockerfile
    image: peagaa/app-integration-api
    ports:
      - 8082:8082
    container_name: app-integration-api
    environment:
      - RABBIT_HOST=rabbitmq_bootcamp
      - POSTGRES_URL=postgres_bootcamp
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamppass
      - POSTGRES_DATABASE=bootcamp
      - CLIENT_ID = 68ba5a78a85b48b9856d1d2c3deccc89
      - CLIENT_SECRET = e404aac43bbe42bca91d9664d2c1ba35
    depends_on:
      - postgres_bootcamp
    networks:
      - backend
networks:
  backend:
    driver: "bridge"